language: python
dist: xenial
sudo: true
python:
  - 3.9
env:
  global:
    - PIPENV_IGNORE_VIRTUALENVS=1
install:
  - pip install pipenv
  - pipenv run sync --dev
script:
  - pipenv run flake8 .
after_success:
  - codecov